(()=>{'use strict';
const IDS=['mwVoiceBtn','mwVoiceStatus','mwRevenue','mwLoadedMi','mwDeadMi','mwOrigin','mwDest','mwLoadNotes','mwEvalOutput'],K={D:'voiceDrafts',C:'voiceCorrections'},A={revenue:['revenue','rate','pay','price','money'],loadedMiles:['loaded miles','loaded','miles'],deadMiles:['deadhead','dead head','empty','dead miles'],origin:['origin','pickup','from'],destination:['destination','drop','deliver to','deliver','to'],notes:['note','notes','comment','comments']},L={revenue:'Revenue',loadedMiles:'Loaded miles',deadMiles:'Deadhead miles',origin:'Origin',destination:'Destination',notes:'Load notes'};let d=null,r=null,on=0,base='',draft=blank(),bound=0;
function blank(){return{id:'voice-'+Date.now(),createdAt:Date.now(),updatedAt:Date.now(),needsReview:1,transcriptSummary:'',fields:{revenue:'',loadedMiles:'',deadMiles:'',origin:'',destination:'',notes:''},confidence:{revenue:0,loadedMiles:0,deadMiles:0,origin:0,destination:0,notes:0},history:[]}}
const j=(v,f)=>{try{return JSON.parse(v)}catch{return f}},g=k=>j(localStorage.getItem(k),[]),s=(k,v)=>localStorage.setItem(k,JSON.stringify(v)),esc=x=>String(x??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m])),norm=t=>String(t||'').replace(/[\u2018\u2019]/g,"'").replace(/[\u201C\u201D]/g,'"').replace(/\s+/g,' ').trim(),num=t=>{t=String(t||'').replace(/[^\d.-]/g,'');t=Number(t);return Number.isFinite(t)?t:null},money=t=>{t=num(t);return t&&t>0?Math.round(t*100)/100:null},miles=t=>{t=num(t);return t!=null&&t>=0?Math.round(t*10)/10:null};
function stat(msg,k='idle'){if(!d?.s)return;if(!msg){d.s.style.display='none';d.s.textContent='';d.s.style.borderColor='var(--accent-border)';d.s.style.color='var(--accent)';return}const p={idle:['var(--accent-border)','var(--accent)'],listening:['var(--accent-border)','var(--accent)'],success:['var(--good-border,rgba(52,211,153,.22))','var(--good,#34d399)'],warn:['var(--warn-border,rgba(251,191,36,.22))','var(--warn,#fbbf24)'],error:['var(--bad-border,rgba(248,113,113,.22))','var(--bad,#f87171)']}[k]||['var(--accent-border)','var(--accent)'];d.s.style.display='';d.s.textContent=msg;d.s.style.borderColor=p[0];d.s.style.color=p[1]}
function btn(a){if(!d?.b)return;d.b.style.display='';d.b.textContent=a?'⏹️':'🎙️';d.b.style.color=a?'var(--accent)':'var(--text-secondary)';d.b.setAttribute('aria-pressed',a?'true':'false');d.b.title=a?'Stop voice input':'Speak load details'}
function keep(){const x=g(K.D),p=clean(draft),i=x.findIndex(v=>v&&v.id===p.id);if(i>=0)x[i]=p;else x.push(p);s(K.D,x.slice(-20))}
function clean(x){return{id:x.id,createdAt:x.createdAt,updatedAt:x.updatedAt,needsReview:!!x.needsReview,transcriptSummary:String(x.transcriptSummary||'').slice(0,240),fields:{...x.fields},confidence:{...x.confidence},history:(Array.isArray(x.history)?x.history:[]).slice(-20)}}
function latest(){const x=g(K.D);return x.length?x[x.length-1]:null}
function fixlog(v){const x=g(K.C);x.push({...v,at:Date.now()});s(K.C,x.slice(-50))}
function conf(v){return v>=85?'high':v>=55?'medium':'low'}
function ccol(v){return v>=85?'var(--good,#34d399)':v>=55?'var(--warn,#fbbf24)':'var(--bad,#f87171)'}
function guide(){const miss=[];if(!draft.fields.revenue)miss.push('revenue');if(!draft.fields.loadedMiles)miss.push('loaded miles');if(!draft.fields.origin)miss.push('origin');if(!draft.fields.destination)miss.push('destination');const v=valid();if(v.ok)return 'Review before apply. Nothing saves automatically.';if(miss.length)return `Say or type “change ${miss[0]} to …” or tap Speak Fix.`;return v.issues[0]||'Review the draft before applying it.'}
function valid(){const q=[],rev=money(draft.fields.revenue),ld=miles(draft.fields.loadedMiles),dh=draft.fields.deadMiles===''?0:miles(draft.fields.deadMiles);if(!rev)q.push('Revenue missing or invalid');if(!ld)q.push('Loaded miles missing or invalid');if(dh==null)q.push('Deadhead miles invalid');if(draft.fields.origin&&draft.fields.origin.length<3)q.push('Origin looks incomplete');if(draft.fields.destination&&draft.fields.destination.length<3)q.push('Destination looks incomplete');return{ok:!q.length,issues:q,rev,ld,dh}}
function pickNum(t,keys){for(const k of keys){const m=t.match(new RegExp(k.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+String.raw`\s*(?:is|to|at|of)?\s*\$?([\d,]+(?:\.\d+)?)`,'i'));if(m)return m[1]}return null}
function pickTxt(t,keys){for(const k of keys){const m=t.match(new RegExp(k.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+String.raw`\s*(?:is|to|as)?\s+([^,.;]+)`,'i'));if(m)return m[1].trim()}return''}
const place=t=>String(t||'').replace(/\b(city|state|zip|pickup|delivery|drop|destination|origin)\b/gi,'').replace(/\s+/g,' ').replace(/^[-,:\s]+|[-,:\s]+$/g,'').trim();
function route(t){for(const p of [/(?:from)\s+(.+?)\s+(?:to)\s+(.+?)(?=$|\b(?:for|pay|rate|loaded|deadhead|note|notes|miles)\b)/i,/^(.+?)\s+to\s+(.+?)(?=$|\b(?:for|pay|rate|loaded|deadhead|note|notes|miles)\b)/i]){const m=t.match(p);if(m)return{origin:place(m[1]),destination:place(m[2])}}return{origin:'',destination:''}}
function parseFix(t){const m=norm(t).match(/^(?:fix|change|update|correct|set)\s+(.+)$/i);if(!m)return null;const src=m[1],lo=src.toLowerCase();let f='';for(const [k,v] of Object.entries(A))if(!f&&v.some(a=>lo.includes(a)))f=k;if(!f)return null;let v=pickTxt(src,A[f])||src.replace(/^(?:revenue|rate|pay|loaded miles|loaded|deadhead|dead head|empty|origin|pickup|destination|drop|deliver(?: to)?|to|note|notes)\s*(?:is|to|as)?\s*/i,'');v=v.trim();if(!v)return null;return{field:f,value:v}}
function parse(t){t=norm(t);const lo=t.toLowerCase(),f={},c={},rt=route(t);if(rt.origin){f.origin=rt.origin;c.origin=72}if(rt.destination){f.destination=rt.destination;c.destination=72}const rv=money(pickNum(t,A.revenue)||(t.match(/\$\s*([\d,]+(?:\.\d+)?)/)||[])[1]);if(rv){f.revenue=String(rv);c.revenue=/\$/.test(t)?92:78}const lm=miles(pickNum(t,['loaded miles','loaded','miles']));if(lm){f.loadedMiles=String(lm);c.loadedMiles=/loaded/.test(lo)?90:63}const dmRaw=pickNum(t,A.deadMiles),dm=miles(dmRaw);if(dmRaw!=null&&dm!=null){f.deadMiles=String(dm);c.deadMiles=/dead|empty/.test(lo)?90:60}const note=pickTxt(t,A.notes);if(note){f.notes=note;c.notes=88}else if(!f.origin&&!f.destination&&t.length>20){f.notes=t.slice(0,240);c.notes=48}const o=pickTxt(t,A.origin);if(o&&!f.origin){f.origin=place(o);c.origin=82}const de=pickTxt(t,['destination','drop','deliver to']);if(de&&!f.destination){f.destination=place(de);c.destination=82}return{fields:f,confidence:c,summary:t.slice(0,240)}}
function merge(p,m={}){draft.updatedAt=Date.now();draft.needsReview=1;for(const k of Object.keys(draft.fields)){if(p.fields&&p.fields[k]!=null)draft.fields[k]=String(p.fields[k]).trim();if(p.confidence&&p.confidence[k]!=null)draft.confidence[k]=p.confidence[k]}if(m.summary)draft.transcriptSummary=m.summary;draft.history.push({at:Date.now(),action:m.action||'parse',summary:m.summary||'',transcript:m.transcript?norm(m.transcript).slice(0,240):''});draft.history=draft.history.slice(-20);keep()}
function restore(){if(d?.o&&base)d.o.innerHTML=base}
function review(){if(!d?.o)return;const v=valid(),rows=Object.keys(L).map(k=>`<div style="display:flex;justify-content:space-between;gap:10px;padding:10px 0;border-top:1px solid var(--border-subtle)"><div style="min-width:0;flex:1"><div style="font-size:11px;text-transform:uppercase;letter-spacing:.4px;color:var(--text-tertiary);font-weight:600">${esc(L[k])}</div><div style="font-size:15px;font-weight:700;line-height:1.4;word-break:break-word">${draft.fields[k]?esc(draft.fields[k]):'<span style="color:var(--text-tertiary)">—</span>'}</div></div><div style="font-size:11px;font-weight:700;white-space:nowrap;color:${ccol(draft.confidence[k]||0)}">${esc((draft.confidence[k]||0)+'% '+conf(draft.confidence[k]||0))}</div></div>`).join(''),box=v.issues.length?`<div style="margin-top:10px;padding:10px 12px;border-radius:10px;background:var(--bad-muted,rgba(248,113,113,.08));border:1px solid var(--bad-border,rgba(248,113,113,.22));font-size:12px;color:var(--bad,#f87171)">${v.issues.map(esc).join('<br>')}</div>`:`<div style="margin-top:10px;padding:10px 12px;border-radius:10px;background:var(--good-muted,rgba(52,211,153,.08));border:1px solid var(--good-border,rgba(52,211,153,.22));font-size:12px;color:var(--good,#34d399)">Structured draft ready for review. Nothing is applied until you tap Apply to Evaluator.</div>`;
 d.o.innerHTML=`<div class="card" style="padding:18px 16px"><div style="display:flex;align-items:center;justify-content:space-between;gap:10px"><div><div style="font-size:18px;font-weight:800">Voice Load Review</div><div style="font-size:12px;color:var(--text-secondary);margin-top:3px">Review before apply. No trip is saved here.</div></div><div style="font-size:11px;color:var(--text-tertiary);font-weight:700">Draft ${esc(draft.id.slice(-6))}</div></div><div style="margin-top:12px;font-size:12px;color:var(--text-secondary)">${esc(guide())}</div><div style="margin-top:8px;border-bottom:1px solid var(--border-subtle)">${rows}</div>${box}<div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px"><button id="vApply" class="btn primary" style="min-height:48px">Apply to Evaluator</button><button id="vFix" class="btn" style="min-height:48px">Speak Fix</button><button id="vKeep" class="btn" style="min-height:44px">Keep Draft</button><button id="vClear" class="btn danger" style="min-height:44px">Clear Draft</button></div></div>`;
 if(!bound){bound=1;d.o.addEventListener('click',e=>{const t=e.target;if(!(t instanceof HTMLElement))return;if(t.id==='vApply')apply();if(t.id==='vFix')listen(1);if(t.id==='vKeep'){keep();stat('Draft kept locally for later review.','success')}if(t.id==='vClear'){draft=blank();localStorage.removeItem(K.D);restore();stat('Voice draft cleared.','idle')}})}}
function apply(){const v=valid();if(!v.ok){stat(v.issues[0]||'Draft needs review before apply.','error');review();return}for(const k of Object.keys(L)){const el=d.f[k];if(!el)continue;el.value=draft.fields[k]||'';el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}))}draft.needsReview=0;draft.updatedAt=Date.now();keep();stat('Structured draft applied to evaluator fields. Review score output below.','success')}
function heard(t,fixMode=0){t=norm(t);if(!t){stat('No speech captured. Try again.','warn');return}const fx=parseFix(t);if(fx){merge({fields:{[fx.field]:fx.value},confidence:{[fx.field]:94}},{action:'fix',summary:`Fixed ${L[fx.field]}`,transcript:t});fixlog({field:fx.field,value:fx.value,transcript:t});stat(`${L[fx.field]} updated. Review the draft below.`,'success');review();return}const p=parse(t);merge(p,{action:fixMode?'speak-fix':'voice-entry',summary:p.summary,transcript:t});const v=valid();stat(v.ok?'Voice draft parsed. Review before applying it to the evaluator.':guide(),v.ok?'success':'warn');review()}
function initRec(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return null;const x=new SR();x.lang='en-US';x.interimResults=false;x.maxAlternatives=1;x.continuous=false;x.addEventListener('result',e=>heard(Array.from(e.results||[]).map(v=>v[0]&&v[0].transcript?v[0].transcript:'').join(' ').trim(),!!x.__fix));x.addEventListener('end',()=>{on=0;btn(0)});x.addEventListener('error',e=>{on=0;btn(0);stat(e.error==='not-allowed'?'Microphone access was denied.':e.error==='no-speech'?'No speech detected. Try again.':'Voice input error. Try again.','error')});return x}
function listen(f=0){if(!r){stat('Voice input is not supported on this device/browser.','error');return}if(on){on=0;btn(0);try{r.stop()}catch{}stat('Voice input stopped.','idle');return}on=1;btn(1);stat(f?'Listening for a fix. Example: “change deadhead to 24”.':'Listening for load details. Nothing will be applied automatically.','listening');try{r.__fix=f;r.start()}catch{on=0;btn(0);stat('Unable to start voice input. Try again.','error')}}
function hydrate(){const x=latest();if(!x){restore();return}draft={...blank(),...x,fields:{...blank().fields,...(x.fields||{})},confidence:{...blank().confidence,...(x.confidence||{})},history:Array.isArray(x.history)?x.history.slice(-20):[]};review();stat('Loaded local voice draft. Review it before applying.','idle')}
function init(){if(IDS.some(id=>!document.getElementById(id)))return;d={b:document.getElementById('mwVoiceBtn'),s:document.getElementById('mwVoiceStatus'),o:document.getElementById('mwEvalOutput'),f:{revenue:document.getElementById('mwRevenue'),loadedMiles:document.getElementById('mwLoadedMi'),deadMiles:document.getElementById('mwDeadMi'),origin:document.getElementById('mwOrigin'),destination:document.getElementById('mwDest'),notes:document.getElementById('mwLoadNotes')}};if(!base)base=d.o.innerHTML;r=initRec();d.b.style.display='';d.b.addEventListener('click',()=>listen(0));btn(0);hydrate();if(!r){d.b.style.display='none';if(latest())stat('Voice input is unavailable here. You can still review a saved voice draft.','warn')}}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init,{once:true}):init();})();
